language: java
sudo: required
dist: xenial
jdk:
  - openjdk8
branches:
  only:
    - master
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - jdk_switcher use openjdk8
  - chmod +x gradlew
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew build